---

- name: Instalamos chrony
  dnf:
    name: chrony
    state: latest
      
- name: Iniciamos el servicio chrony y lo habilitamos.
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true

- name: Desahabilitamos SELinux
  selinux:
    state: disabled