---

- name: Copiamos el fichero /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  
- name: Nos aseguramos que firewalld esté activado
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Añadimos el modulo br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Permitimos masquerade en el FW.
  command: firewall-cmd --add-masquerade --permanent

- name: Reiniciamos firewalld
  systemd:
    name: firewalld
    state: restarted
    
- copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644


- name:  Ejecutamos sysctl --system
  command: sysctl --system