---

- name: Configuiramos el repo
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: instalamos la version docker-ce-20.10.6-3.el8.
  dnf:
    name: docker-ce-20.10.6-3.el8
    state: present

- name: Iniciamos el servicio Docker y lo habilitamos.
  systemd:
    name: docker
    state: restarted
    enabled: yes
