---

- name: Configuiramos el repo
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: instalamos la version docker-ce-20.10.6-3.el8.
  dnf:
    name: docker-ce-20.10.6-3.el8
    state: present

- name: Iniciamos el servicio Docker y lo habilitamos.
  systemd:
    name: docker
    state: restarted
    enabled: yes

- copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Instalamos kubernetes.
  command: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- name: Iniciamos el servicio kubelet y lo habilitamos.
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
