---

- name: Creamos el directorio para desplegar la app de kubernetes.
  file:
    path: /opt/app/
    state: directory
    mode: "0744"

#Copiamos el fichero con la config para lanzar la aplicación en kubernetes.

- copy:
    src: files/app.yaml
    dest: /opt/app/app.yaml
    mode: 0744
- name: Creamos el namespace.
  command: kubectl create namespace webapp-routed

- name: Desplegamos la aplicación.
  command: kubectl apply -f /opt/app/app.yaml

- copy:
    src: files/ingress.yaml
    dest: /opt/app/ingress.yaml
    mode: 0744
 
- name: Desplegamos la Ingress.
  command: kubectl apply -f /opt/app/ingress.yaml
 
- name: Desplegamos ingress.
  command: kubectl describe ingress webapp-ingress --namespace=webapp-routed

- copy:
    src: files/configmap.yaml
    dest: /opt/app/configmap.yaml
    mode: 0744
 
- name: Desplegamos la Configmap.
  command: kubectl apply -f /opt/app/configmap.yaml
