- name: Configuración para los workers.
  hosts: all
  become: yes
  
  vars_prompt:
    - name: "token"
      prompt: "Introduce el token que se ha mostrado por pantalla en la tarea anterior con nombre: Instalamos el plugin CNI (Container Network Interface) de kubernetes"
      private: yes
    
  roles:
    - workers