- name: Configuración para los workers.
  hosts: all
  become: yes
  
  vars_prompt:
    - name: "token"
      prompt: "Introduce el token que se ha mostrado por pantalla"
      private: yes
    
  roles:
    - workers
