---
#Comenzamos el script pidiendo el token que emos mostrado por pantalla anteriormente, sino no podemos unir los workers al nodo.

vars_prompt:
- name: "token"
  prompt: "Introduce el token que se ha mostrado por pantalla en la tarea anterior con nombre: Instalamos el plugin CNI (Container Network Interface) de kubernetes"
  private: yes

- firewalld:
    port: 10250/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 30000-32767/tcp
    permanent: true
    state: enabled

- name: Reiniciamos firewalld
  systemd:
    name: firewalld
    state: restarted

- name: Añadiendo los workers al nodo.
  command: kubeadm join 192.168.1.110:6443 --token "{{ token }}"

#damos tiempo a los workers a ponerse como ready.

#- pause:
#    minutes: 2