---

- copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Instalamos kubernetes.
  command: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- name: Iniciamos el servicio kubelet y lo habilitamos.
  systemd:
    name: kubelet
    state: restarted
    enabled: yes


# Configuramos reglas en el FW del master.

- firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 2379-2380/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 10250-10252/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 10255/tcp
    permanent: true
    state: enabled

- name: Reiniciamos firewalld
  systemd:
    name: firewalld
    state: restarted


- name: Configuramos kudeadm.
  command: kubeadm config images pull

########## FIREWALLD #################
#Permitiremos el acceso desde los workers

- firewalld:
    source: 192.168.2.101/32
    permanent: true
    state: enabled

- firewalld:
    source: 192.168.2.102/32
    permanent: true
    state: enabled

#Permitimos Local Host.

- firewalld:
    source: 172.17.0.0/16
    permanent: true
    state: enabled
    

- name: Reiniciamos firewalld
  systemd:
    name: firewalld
    state: restarted

- name: Instalamos el plugin CNI (Container Network Interface) de kubernetes y definimos la red de los PODs.
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: kubeadm
# Pintamos por pantalla la salida, de esta manera podemos copiar el token.
- name: debug
  debug: msg="{{ kubeadm.stdout }}"



